DEEPSORT:
  REID_CKPT: "/mnt/37c00eec-d043-4088-b730-36c9e48a38e4/deep_sec/object_trackers/deep_sort/checkpoint/ckpt.t7"
  MAX_DIST: 0.2
  MIN_CONFIDENCE: 0.3
  NMS_MAX_OVERLAP: 0.5
  MAX_IOU_DISTANCE: 0.7
  MAX_AGE: 70
  N_INIT: 3
  NN_BUDGET: 100

